# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Gayle Shim
description: "Hi, I'm Gayle, and I'm an aspiring Data Analyst with a background in research focused on social impact and real-world decision-making.  My portfolio showcases projects where I apply data analysis to practical problems, with an emphasis on generating meaningful, actionable insights.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Caersws, UK"
resume_url: /docs/resume.docx
avatar_image: img/GayleShim.png

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/#" # Add your linkedln handle
github: "https://github.com/Gayle-Shim.github.io"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

